version: "3.9"

networks:
  bolt_net:
    driver: bridge

services:
  db:
    image: postgres:18.1
    container_name: bolto-db-container
    restart: unless-stopped
    ports:
      - "5192:5432"
    environment:
      POSTGRES_DB: bolto-db
      POSTGRES_USER: bolto-user
      POSTGRES_PASSWORD: "sdfsd#rfetDGFDGd5ftydewftyd5y%$"
    volumes:
      - /data/bolto/postgres:/var/lib/postgresql
    networks:
      - bolt_net

  api:
    image: novakvova/bolto-api:latest
    container_name: bolto-api-container
    restart: unless-stopped
    volumes:
      - /data/bolto/images:/app/images
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=bolto-db;Username=bolto-user;Password=sdfsd#rfetDGFDGd5ftydewftyd5y%$"
    ports:
      - "127.0.0.1:3589:8080"
    depends_on:
      - db
    networks:
      - bolt_net

 