version: "3.9"

networks:
  bolt_net:
    driver: bridge

services:
  db:
    image: postgres:18.1
    container_name: bolto-db-container
    restart: unless-stopped
    ports:
      - "5192:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${VOLUME_POSTGRES}
    networks:
      - bolt_net

  api:
    image: 0taras0/bolto-api:latest
    container_name: bolto-api-container
    restart: unless-stopped
    volumes:
      - ${VOLUME_SERVERAPI}
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    ports:
      - "127.0.0.1:3589:8080"
    depends_on:
      - db
    networks:
      - bolt_net

 